### ISSUE TITLE
Question(or feature request) about injecting class names via tags

### ISSUE THREAD

**Issue by MostHated** [UnityGuillaume/MarkdownRenderer#3]
Hey there,
        I  am a big fan of this package, I have been using it in conjunction with the TutorialFramework to be able to make tutorial pages using Markdown. What I found that would be extremely useful would be the ability to use a tag to assign a USS class to whatever VisualElements are created within the tag. For example:

I was wanting to use UIElement Query to access the quote block elements, but noticed that there was no solid way to differentiate one element from another similar element. I could do something like the following to manually assign class names to specific elements:

```cs
StyleColor quoteBorder = new StyleColor("#FF5700".FromHex());
var renderRoot = m_Root.tutorialPageContainer.Query<VisualElement>(name: "RendererRoot").First();
if (renderRoot != null)
{
    renderRoot[3].style.borderLeftColor = quoteBorder;
    renderRoot[3].AddToClassList("quoteBlockOne");

    renderRoot[7].style.borderLeftColor = quoteBorder;
    renderRoot[7].AddToClassList("quoteBlockTwo");
}
```
<details>
<summary>Result</summary>

![result-image](https://img.instance.id/oCdtQCRZb9EW/direct)

</details>

But it would be quite helpful to be able to do something such as this on the Markdown side, and have it applied to the generated UIElements:

```markdown
<class="quoteBlockTwo">  <!-- or [class="quoteBlockTwo"], etc. Syntax can be whatever works best/interferes less with existing parsing -->
>**If no GameObject is assigned to the **Search Filter** field, the system will attempt to match all GameObjects in the hierarchy.**
</class>
```

That is just one example, but I use class names a lot to fire off events to perform animations and custom highlighting of specific elements, and it would be a huge help to be able to quickly and easily assign specific class names to elements ahead of time.

I have not looked super deep yet into the command system that is built into this package, but from what I did see, it seems like it is more for performing actions based in links. Is there any mechanism that exists in the package currently that might allow for something like this, or would I end up having to add a whole new type of Renderer or Handler? 

I might try and play around and see if I can come up with something but wanted to at least throw it out there in case there happened to be something I just missed, or you might have an idea already of a quicker way to implement something like this?

Thanks,
-MH

**Comment by UnityGuillaume** [comment]
Hum good suggestion. As the system use Markdig as its parser, I will have a look at it, there's probably a way to add extension to it or markdig may even already support handling custom tag.

**Comment by MostHated** [comment]
My apologies, somehow I missed that you had replied. I just gave this a go, and seems to be working just as I had hoped. The additional frontmatter support for loading additional USS files is a nice surprise as well. Much appreciated. :+1:
