### ISSUE TITLE
Can't seem to assign a class to an image using the new generic attributes feature

### ISSUE THREAD

**Issue by MostHated** [UnityGuillaume/MarkdownRenderer#5]
Hey again,
   I think there might be a slight bug in trying to assign a class to an image. I tried it a few ways, based on what I saw in the generic attribute link in the Readme. Behind the link tags, above as a block, as well as in front/inline, but none of them seem to actually attach the class to the image.

```md
<!-- This seemed to not include the class at all, though I think it is the correct method to use based on the example of
[This is a link](http://google.com/){#a-link .myclass data-lang=fr data-value="This is a value"} -->

![Image](search:pst_7_loadingMenu_image_psTutorial){.loadingMenuImage} 

<!-- Both this: -->
{.loadingMenuImage}
![Image](search:pst_7_loadingMenu_image_psTutorial)

<!-- And this had similar results as seen below -->
{.loadingMenuImage} ![Image](search:pst_7_loadingMenu_image_psTutorial)

```

The latter two attempts might actually be doing what they are supposed to be doing, I am not quite sure. Creating a new parent VisualElement with an empty label containing the class, instead of the Image element below it.

![](https://img.instance.id/lb0cRBXTKSqo/direct)

Thanks,
-MH

**Comment by MostHated** [comment]
A few other side notes, I have been having to go in and make a bunch of changes because my asset is a package, so none of my stuff is in the Assets folder, it is all in Packages/

For example, in MarkdownViewer.cs, I had to add the following along with "search:"

```csharp
        else if (link.StartsWith("package"))
        {
            //this is a relative link, so find the actual link
            link = link.Replace("package:", "");

            var searchStr = $"a:packages {link}";
            var files = AssetDatabase.FindAssets(searchStr);

            if (files.Length == 0)
            {
                Debug.LogError($"Couldn't find link : {link}");
                return;
            }

            var path = AssetDatabase.GUIDToAssetPath(files[0]);
            Selection.activeObject = AssetDatabase.LoadAssetAtPath<Object>(path);
        }
```

--- 
Then for the packages asmdef file, it is named "Unity.Rtl.MarkdowRenderer.Editor.asmdef", but the actual value in it is `"name": "Unity.[SubGroup].[YourPackageName].Editor",` (https://github.com/UnityGuillaume/MarkdownRenderer/blob/c9a90c64027f659efd3ff3fd05a6a14944336e5d/Editor/Unity.Rtl.MarkdowRenderer.Editor.asmdef#L2C5-L2C57)

I was going to prepare a PR for this, but I didn't know if you accepted PR's, a lot of Unity packages don't?

**Comment by UnityGuillaume** [comment]
Sorry I can only work on that when I got some free time, so only getting to this now. I'll have a look for the image attribute problem.

I also need to make clearer that though I work at Unity, this is a personal project and not an official package in any shape or form. I'll happily take a PR, as Packages are indeed a good use cases and didn't though about handling package link.
For this case though, probably easier for me to redo it since you provided the code, and I'll use that time to also cleanup/update package name and the like.

**Comment by UnityGuillaume** [comment]
Ok this should be fixed. Latest on main should handles :

- image now have correct class applied. As you correctly did the first time, the right way is to add the class AFTER the image. Before the image renderer in the Markdown Renderer wasn't getting the class to add the the UIElement class list. This should be now corrected.
- typo in name, and changed the name of the package everywhere to just be rtl.markdownrenderer, removing the unity reference to not create confusion about the fact that this package isn't an official package
- **better handling of path** : paths now properly handle :
    - Absolute path like `Assets/folder/file.png` and `Packages/com.packagename/file.md` 
    - Relative path _inside packages_ so a `./my_image.png` path on a markdown inside a package will currently look in the package folder, next to the md file and not inside the Assets folder anymore.
    - Also added a `package:` "special path" that is a search path only searching through packages, ignoring the Assets folder


As usual feel free to reopen an issue if there is corner cases I miss as I'm not very good at QA so I have no doubt I missed some possibilities somewhere.
